# Generated by Django 3.1 on 2020-09-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='Faves', to='recipe_box.Recipe'),
        ),
    ]
